Wiki_added_text:
  type: string
  default: 'Revision History of this Wiki'
  description: 'Text to be placed next to the edits icon in the top right corner of the post. Leave blank if no text is desired'
  
Shared_edits_hide:
  type: enum
  default: 'No'
  choices:
    - 'Yes'
    - 'No'
  description: 'Disable the edit button in the post review panel?<br>This eliminates the chance of a clash if the Shared Edits plugin is being used.'
