Wiki_post_background_color:
  type: string
  default: green
  description: 'Enter a background color for your wiki posts.<br> Colors can be by name e.g. blue, green red, yellow, black, white<br>You can also enter primary, secondary, tertiary, quaternary, highlight, danger, success, and love to match your theme color settings.<br>For FIXED colors you can also enter a html code e.g. #0066CC. PLEASE NOTE you must set the opacity to 100% if using the html color codes.'

Wiki_opacity:
  type: enum
  default: 15%
  choices:
    - 5%
    - 10%
    - 15%
    - 25%
    - 35%
    - 50%
    - 75%
    - 100%
  description: 'Select the opacity of the Wiki background colour. The larger the percentage the deeper the colour<br>The bubble color is blended with the theme background color. This enables the color to adjust to light and dark theme settings.<br>PLEASE NOTE when usimg html color codes (e.g. #00FF00) you must set the opacity to 100%'
  
Wiki_added_text:
  type: string
  default: 'Wiki Post'
  description: 'Text to be placed next to the edits icon in the top right corner of the post. Leave blank if no text is desired'
  
